name: Browser Extension CD

on:
  push:
    tags:
       - 'v*'

jobs:
  build_release:
    runs-on: ubuntu-20.04
    name: create release

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 16

    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: version
      run: echo ::set-output name=version::${GITHUB_REF#refs/*/}
      id: version

    - name: Build artifact
      run: |
          npm ci
          npm run build
          sudo apt install zip
          zip -rm FraudGuard.windows-amd64.zip dist

    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./FraudGuard.windows-amd64.zip
        tag: ${{ github.ref }}
        overwrite: true
        file_glob: true
